const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  transpileDependencies: true,
  pwa: {
    name: 'Parole Evocatrici',
    display: 'fullscreen',
    themeColor: '#4DBA87', // slate green
    workboxOptions: {
      exclude: [/_redirects/]
    },
    assetsVersion: 1 // against cache
  },
  pluginOptions: {
    sitemap: {
      urls: [
        'https://parole-evocatrici.com',
        'https://parole-evocatrici.com/metodi',
        'https://parole-evocatrici.com/random',
        'https://parole-evocatrici.com/newWord',
        'https://parole-evocatrici.com/leggi-psicologiche',
        'https://parole-evocatrici.com/spiegazione-tecnica-parole-evocatrici',
        'https://parole-evocatrici.com/blog',
        'https://parole-evocatrici.com/blog/parole-evocatrici.com-e-una-pwa',
        'https://parole-evocatrici.com/blog/frasi-roberto-assagioli',

        "https://parole-evocatrici.com/word/Contemplazione",
        "https://parole-evocatrici.com/word/Fede",
        "https://parole-evocatrici.com/word/Audacia",
        "https://parole-evocatrici.com/word/Serenità",
        "https://parole-evocatrici.com/word/Reverenza",
        "https://parole-evocatrici.com/word/Beatitudine",
        "https://parole-evocatrici.com/word/Leggerezza",
        "https://parole-evocatrici.com/word/Determinazione",
        "https://parole-evocatrici.com/word/Gratitudine",
        "https://parole-evocatrici.com/word/Forza",
        "https://parole-evocatrici.com/word/Iniziativa",
        "https://parole-evocatrici.com/word/Elevazione",
        "https://parole-evocatrici.com/word/Verità",
        "https://parole-evocatrici.com/word/Perseveranza",
        "https://parole-evocatrici.com/word/Ordine",
        "https://parole-evocatrici.com/word/Ammirazione",
        "https://parole-evocatrici.com/word/Positività",
        "https://parole-evocatrici.com/word/Vigilanza",
        "https://parole-evocatrici.com/word/Equilibrio",
        "https://parole-evocatrici.com/word/Disciplina",
        "https://parole-evocatrici.com/word/Gioia",
        "https://parole-evocatrici.com/word/Liberazione",
        "https://parole-evocatrici.com/word/Quiete",
        "https://parole-evocatrici.com/word/Sintesi",
        "https://parole-evocatrici.com/word/Consacrazione",
        "https://parole-evocatrici.com/word/Calma",
        "https://parole-evocatrici.com/word/Amicizia",
        "https://parole-evocatrici.com/word/Riflessione",
        "https://parole-evocatrici.com/word/Apprezzamento",
        "https://parole-evocatrici.com/word/Entusiasmo",
        "https://parole-evocatrici.com/word/Creatività",
        "https://parole-evocatrici.com/word/Solidarietà",
        "https://parole-evocatrici.com/word/Servizio",
        "https://parole-evocatrici.com/word/Semplicità",
        "https://parole-evocatrici.com/word/Silenzio",
        "https://parole-evocatrici.com/word/Rispetto",
        "https://parole-evocatrici.com/word/Volontà",
        "https://parole-evocatrici.com/word/Volontà buona",
        "https://parole-evocatrici.com/word/Luce",
        "https://parole-evocatrici.com/word/Umorismo",
        "https://parole-evocatrici.com/word/Libertà",
        "https://parole-evocatrici.com/word/Interezza",
        "https://parole-evocatrici.com/word/Generosità",
        "https://parole-evocatrici.com/word/Infinito",
        "https://parole-evocatrici.com/word/Concentrazione",
        "https://parole-evocatrici.com/word/Decisione",
        "https://parole-evocatrici.com/word/Integrazione",
        "https://parole-evocatrici.com/word/Saggezza",
        "https://parole-evocatrici.com/word/Persistenza",
        "https://parole-evocatrici.com/word/Pazienza",
        "https://parole-evocatrici.com/word/Rinnovamento",
        "https://parole-evocatrici.com/word/Amore",
        "https://parole-evocatrici.com/word/Eternità",
        "https://parole-evocatrici.com/word/Prontezza",
        "https://parole-evocatrici.com/word/Discernimento",
        "https://parole-evocatrici.com/word/Compassione",
        "https://parole-evocatrici.com/word/Inclusività",
        "https://parole-evocatrici.com/word/Bontà",
        "https://parole-evocatrici.com/word/Energia",
        "https://parole-evocatrici.com/word/Universalità",
        "https://parole-evocatrici.com/word/Pace",
        "https://parole-evocatrici.com/word/Distacco",
        "https://parole-evocatrici.com/word/Armonia",
        "https://parole-evocatrici.com/word/Coraggio",
        "https://parole-evocatrici.com/word/Comprensione",
        "https://parole-evocatrici.com/word/Bellezza",
        "https://parole-evocatrici.com/word/Realtà",
        "https://parole-evocatrici.com/word/Sacralità",
        "https://parole-evocatrici.com/word/Tenacia",
        "https://parole-evocatrici.com/word/Attenzione",
        "https://parole-evocatrici.com/word/Collaborazione",
        "https://parole-evocatrici.com/word/Risolutezza",
        "https://parole-evocatrici.com/word/Stupore",
        "https://parole-evocatrici.com/word/Vitalità",
        "https://parole-evocatrici.com/word/Costanza",
        "https://parole-evocatrici.com/word/Accettazione"
      ]
    }
  }
})
